import type { ZenSettings } from './types';

export const DEFAULT_SETTINGS: ZenSettings = {
  enabled: true,
  shorts: true,
  home: false,
  playlists: true,
  liked: true,
  yourVideos: true,
  downloads: true,
  subscriptions: true,
  navigator: true,
  explore: true,
  reportButton: true,
  footer: true,
  fixUblock: true,
  actionPanel: true,
  headerMenuButton: false,
  youList: true,
  youMyChannel: false,
  youHistory: false,
  youWatchLater: false,
  navMusic: true,
  navFilms: true,
  navLive: true,
  exploreMusic: true,
  exploreKids: true,
  activeSection: 'cleaner',
  filterWatchedEnabled: false,
  filterWatchedThreshold: 20,
  filterSearchUploadDate: 'any',
  filterSearchDuration: 'any',
  filterSearchSort: 'relevance',
  filterSearchType: 'any',
};
